language: node_js
node_js:
  - "13"
install:
  - npm install
script:
  - npm run lint && npm run build
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: pZLjgvKWnSwfj4LNa1GY1bMYDQqLCEduXzQm9ZY/Yt/5shv1Kaw3iAqmV41NuJGSgCxojHkkwa5UHeQPmMg8B0kJSS4alILxdMqNipPtaSyQhs6LKW9yAjHw2CTwkX2Qzt4K8/0WS5w/jC3LKCp2yYlX1DwVVNmcFQPMvdod6dbvPLyip1HJr8v0Aqv6c69UX/amZI2NzhLi8pNzpeT9rMOuetOLU25Il//sP7QwwO5ye9xBg808SjQa/DqG2fKWU4roBFCF1b0g+sOGga5w+bw80KCJ4jpNyxTZpJejr8DYXU53yHUBXpL/VAjScKxpWqgzwqxuxaKePc86jPIlG1tAaKT/jT25r0EByQrvcEFmy93W1as/rJZQ1/6jgtZBm/99dkE2rOpQ9+tId4PHm6HdwFKjksx6E5NK49Le5GbhMKQzyw+d8s5ijTFrSfVUiFtBC88t5fsVfAEo4uof21UoPGDV8A3SkNCQUZpJS7zBBUnMpnYZG9oUKCZ6CgkUnX93ZwueMsr9G48m0h5fKz58r4mlj8DBJ6cqswvarxLLwBtfWpQ0AvIOgVP4XslN6I88JCzwcfaPud6S2YUBPz/biMnelU51ZB62/FK11T8X7niBqXigR4zQAScYedvW2ASJcyHYpl/l0umEeTJ70/83D2dC5xWaBoz/+dTZRwQ=
  app:
    master: ac-critter-tracker-prd
    dev: ac-critter-tracker
